[package]
name = "notes-reminder"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls", "postgres", "uuid", "chrono" ] }
tokio = { version = "1.28", features = ["full"] }
serde_json = "1"
chrono = "0.4"
futures = "0.3"
dotenv = "0.15"
rand = "0.8"
uuid  = { version = "1.3", features = ["v4"] }
regex = "1.8"
teloxide = "0.12"
log = "0.4"
env_logger = "0.10.0"
