[package]
name = "notes-reminder"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = [ "runtime-async-std-native-tls", "postgres", "macros", "uuid", "chrono", "json" ] }
tokio = { version = "1.28", features = ["full"] }
serde_json = "1"
chrono = "0.4"
futures = "0.3"
dotenv = "0.15"
