version: '3'

services:
  notes-reminder-bot:
    image: kunansy/notes_reminder:1.2.0
    container_name: notes-reminder-bot
    env_file: .env
    restart: always
    entrypoint: ["python3", "reminder/main.py", "--start"]
    networks:
      - readingtracker_tracker-net
    healthcheck:
      test: "exit 0"

  notes-reminder:
    image: kunansy/notes_reminder:1.2.0
    container_name: notes-reminder
    env_file: .env
    restart: always
    entrypoint: ["/srv/cronn", "-c", "@every ${REPEAT}m python3 reminder/main.py --remind"]
    depends_on:
      - notes-reminder-bot
    networks:
      - readingtracker_tracker-net
    healthcheck:
      test: "exit 0"

networks:
  readingtracker_tracker-net:
    external: true
