version: '3'

x-img: &img
    image: kunansy/notes_reminder:2.1.2

services:
  notes-reminder-bot:
    <<: *img
    container_name: notes-reminder-bot
    env_file: .env
    restart: always
    entrypoint: ["/app/app", "--start"]
    networks:
      - tracker-net
    healthcheck:
      test: "exit 0"

  notes-reminder:
    <<: *img
    container_name: notes-reminder
    env_file: .env
    restart: always
    entrypoint: ["/srv/cronn", "-c", "@every ${REPEAT}m /app/app --remind"]
    depends_on:
      - notes-reminder-bot
    networks:
      - tracker-net
    healthcheck:
      test: "exit 0"

  repeat-reminder:
    <<: *img
    container_name: repeat-reminder
    env_file: .env
    restart: always
    entrypoint: ["/srv/cronn", "-c", "0 ${WEEKEND_REPEAT_HOUR} * * 5-6 /app/app --repeat"]
    depends_on:
      - notes-reminder-bot
    networks:
      - tracker-net
    healthcheck:
      test: "exit 0"

networks:
  tracker-net:
    external: true
