version: '3'

services:
  notes-reminder-bot:
    image: kunansy/notes_reminder:2.0.5
    container_name: notes-reminder-bot
    env_file: .env
    restart: always
    entrypoint: ["/app/app", "--start"]
    networks:
      - readingtracker_tracker-net
    healthcheck:
      test: "exit 0"

  notes-reminder:
    image: kunansy/notes_reminder:2.0.5
    container_name: notes-reminder
    env_file: .env
    restart: always
    entrypoint: ["/srv/cronn", "-c", "@every ${REPEAT}m /app/app --remind"]
    depends_on:
      - notes-reminder-bot
    networks:
      - readingtracker_tracker-net
    healthcheck:
      test: "exit 0"

networks:
  readingtracker_tracker-net:
    external: true
